disabled_rules:
  - trailing_whitespace
  - colon
  - comma
  - control_statement
  - force_try
opt_in_rules:
  - empty_count
  - empty_string
excluded:
  - Carthage
  - Pods
  - SwiftLint/Common/3rdPartyLib
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
line_length:
    warning: 200
    error: 250
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_name:
    min_length: 4
    max_length:
    warning: 40
    error: 50
identifier_name:
    min_length:
    error: 4
    excluded:
      - id
      - URL
      - GlobalAPIKey
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
